### ISSUE TITLE
Enable passing hints from JPA to JDBC

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner-jdbc#1117]
JPA allows applications to set vendor-specific hints. 'vendor' in this case is the JPA provider (e.g. Hibernate). One possible hint in Hibernate is a `COMMENT` hint (`"org.hibernate.comment"`). Such comment hints could be used to pass hints along to the Cloud Spanner JDBC driver, and then be translated into actual query hints or other features, e.g.
* Hints to add a table/index hint (FORCE_INDEX)
* Hints to add a statement hint (OPTIMIZER_VERSION)
* Hints to add a statement tag / transaction tag.

**Comment by pkkht** [comment]
Hello, I would like to contribute to this repository and would like to work on this, if that's ok!

**Comment by olavloite** [comment]
The feature has been implemented in the Hibernate dialect here: https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/940
