### ISSUE TITLE
Relocate common / widely used runtime dependencies in shaded jar

### ISSUE THREAD

**Issue by jeffersonatsafe** [googleapis/java-spanner-jdbc#316]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
We're trying to integrate the shaded jar in our project. However, our project is large and is dependent on older versions of some of the commonly used runtime dependencies (eg: protobuf, guava). When we add the shaded driver jar into our classpath, we're running into dependency conflicts. 

**Describe the solution you'd like**
runtime dependencies in the shaded jar would be relocated with a shaded pattern. 

**Describe alternatives you've considered**
We considered updating the dependencies in our project, but it is not feasible at the moment. 

Thanks for considering this request!

**Comment by olavloite** [comment]
@jeffersonatsafe Would you mind trying out the profile in #333 and see if that works for you?

**Comment by jeffersonatsafe** [comment]
@olavloite the profile in #333 works! thank you so much!
