### ISSUE TITLE
Spanner JDBC Driver: getTimestamp(index, Calendar) ignores the Calendar timezone

### ISSUE THREAD

**Issue by hmxxyy** [googleapis/java-spanner-jdbc#329]
getTimestamp call with Calendar doesn't work. It just ignores the Calendar timezone completely.

#### Environment details

1. Spanner JDBC Driver
2. OS type and version: Mac OS Catalina
3. Java version: "1.8.0_211"
4. spanner-jdbc version(s): 1.18.3

#### Steps to reproduce
Run the following code, no matter what timezone is set in the Calendar, it always uses the local timezone

#### Code example

            try (ResultSet rs = statement.executeQuery(
                  "SELECT CURRENT_TIMESTAMP() as now, STRING(CURRENT_TIMESTAMP(), 'UTC') now_in_string"
            )) {
                while (rs.next()) {
                    java.sql.Timestamp timestamp = rs.getTimestamp(1);
                    java.util.Calendar cal = Calendar.getInstance();
                    cal.setTimeZone(TimeZone.getTimeZone("UTC"));
                    java.sql.Timestamp timestampUTC = rs.getTimestamp(1, cal);
                    String timestampInString = rs.getString(2);
                    System.out.println(timestamp + "|" + timestampUTC + "|" + timestampInString);
                }
            }

#### Output
2021-01-22 16:02:08.472888669|2021-01-22 16:02:08.472888669|2021-01-23 00:02:08.472888669+00

#### Expected output
2021-01-22 16:02:08.472888669|2021-01-23 00:02:08.472888669|2021-01-23 00:02:08.472888669+00
timestampUTC should be UTC time, not the client side time (PST)

**Comment by olavloite** [comment]
@hmxxyy Thanks for the report. I think there is a small misunderstandings here:
1. Cloud Spanner will always return a `TIMESTAMP` value in UTC (including the timezone identifier 'Z'). The JDBC driver therefore knows exactly what the point in time is.
2. `java.sql.Timestamp` does __not__ contain any independent timezone information. It always uses the default timezone of the local JVM. So when you call `java.sql.Timestamp#toString()` you will always get the value in your local timezone.
3. The JDBC method `ResultSet#getTimestamp(int, Calendar)` is not intended to convert a timestamp with known timezone information to a different timezone. This would also be impossible, as its return type is `java.sql.Timestamp` and does not have its own timezone. Instead, this method (and similar methods) are intended to interpret a database timestamp value __without any timezone information__ as being in a specific timezone. You should therefore normally only use this method if the database timestamp that you are reading does not contain any timezone information, or you deliberately want to ignore the timezone information in the timestamp. This is hardly ever relevant with Cloud Spanner.

Point 3 above means that if the database value is `2021-01-22T16:02:08.472888669Z` and you read it using a `Calender` with timezone `PST`, the timestamp will be interpreted as `2021-01-22T16:02:08.472888669-09:00`.

See also the documentation for the method: https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#getTimestamp(int,%20java.util.Calendar)

Consider the following example:

```java
      try (java.sql.ResultSet rs = connection.createStatement().executeQuery("SELECT CURRENT_TIMESTAMP(), STRING(CURRENT_TIMESTAMP(), 'UTC')")) {
        while(rs.next()) {
          // Print out the string value from the backend.
          System.out.printf("Backend timestamp: %s%n", rs.getString(2));
          
          // This retrieves the timestamp based on the timezone information in the timestamp itself.
          // This is what you would normally want to do, as Cloud Spanner does store timezone information.
          // java.sql.Timestamp itself does NOT store any timezone information, which is why it will
          // always be printed in the local timezone of the JVM.
          java.sql.Timestamp tsLocal = rs.getTimestamp(1);
          System.out.printf("Now jdbc (no calendar): %s%n", tsLocal);
          
          // This will read it as if it was a UTC timestamp (i.e. no difference with the backend, as that is what the timestamp is).
          java.sql.Timestamp tsUtc = rs.getTimestamp(1, utc);
          System.out.printf("Now jdbc (UTC calendar): %s%n", tsUtc);
          
          // This will read the timestamp as if it was a PST timestamp (what it is not). This will change the value of the timestamp.
          java.sql.Timestamp tsPst = rs.getTimestamp(1, pst);
          System.out.printf("Now jdbc (PST calendar): %s%n", tsPst);
        }
      }
```

This will print out the following on my computer in CET:

```
Backend timestamp: 2021-01-25 09:51:08.655791244+00
Now jdbc (no calendar): 2021-01-25 10:51:08.655791244
Now jdbc (UTC calendar): 2021-01-25 10:51:08.655791244
Now jdbc (PST calendar): 2021-01-25 02:51:08.655791244
```

The printed out values on a client running in PST will be different, as `java.sql.Timestamp#toString()` always returns the value in the local timezone.

**Comment by hmxxyy** [comment]
Thanks @olavloite for the detailed explanation. It makes senses now.
