### ISSUE TITLE
Documentation for connection properties are not formatted correctly.

### ISSUE THREAD

**Issue by HailongWen** [googleapis/java-spanner-jdbc#342]
#### External references such as API reference guides

When reviewing the [API documentation for JdbcDriver](https://googleapis.dev/java/google-cloud-spanner-jdbc/latest/index.html), I found that the content for `optimizerVersion` is not well-formatted. For the source, it seems that it missed a [closing code block element](https://github.com/googleapis/java-spanner-jdbc/blob/9b53df4ea33926d9fa0955a4445c2ea6790ac3dc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java#L92).

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by olavloite** [comment]
@HailongWen Thanks, good spot!
