### ISSUE TITLE
Encoded-key based authentication 

### ISSUE THREAD

**Issue by Journerist** [googleapis/java-spanner-jdbc#486]
It is a common and suggested use case to use spring data cloud spanner and spanner-jdbc for liquibase for application based database migrations. When you use spring data spanner, one recommended way is to set `spring.cloud.gcp.spanner.credentials.encoded-key` that contains a base64 encoded service account json to setup authentication.

It would be very beneficial if spring jdbc uses and supports this way of credential providing too. Right now, I workaround by defining a conditional initializer that creates a credentials file on application startup and reference the created file via connection url `jdbc:cloudspanner:/projects/my-project/instances/my-instance/databases/my-db;credentials=/path/to/credentials.json`.

does it make sense that you also accept the encoded-key via a Connection property, or via some other mechanism that behaves similar to the concept of spring data spanner?

thanks in advance!

**Comment by Journerist** [comment]
Awesome, thank you! Will give it a try ASAP.

**Comment by olavloite** [comment]
> Awesome, thank you! Will give it a try ASAP.

Oh, I'm afraid I should have phrased my 'Fixes' comment a little bit differently. The change in https://github.com/googleapis/java-spanner/pull/1223 will implement this feature, but only once the JDBC driver picks up the latest version of the Spanner client library. So even if you pull the main branch of the JDBC driver now, you will not automatically get this feature. If you really want to test it out today, you would need to clone both the Java client library and the JDBC driver, and update the reference in the JDBC driver to the client library to use your local version.
