### ISSUE TITLE
Vulnerable version of gson

### ISSUE THREAD

**Issue by husseyd** [googleapis/java-spanner-jdbc#657]
Hi guys,

SCA vulnerability scanner is picking up a High "Deserialization of Untrusted Data" vulnerability in the version of GSON used by this library.

https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327
com.google.cloud:google-cloud-spanner-jdbc@2.4.5 › com.google.code.gson:gson@2.8.8

The issue is apparently resolved in gson@2.8.9 - could you please bump up the version? We use this spanner-jdbc library across many services so vulnerable reports are heavily polluted.

**Comment by thiagotnunes** [comment]
Thanks for the report, we are taking a look!

**Comment by husseyd** [comment]
Just realised I has spanner-jdbc@2.4.5 but the same issue exists in 2.5.1. Thanks!

**Comment by thiagotnunes** [comment]
We now have version 2.8.9 of gson in the library.

Earliest version with the fix is [2.5.3](https://github.com/googleapis/java-spanner-jdbc/blob/main/CHANGELOG.md#253-2021-11-15)
