### ISSUE TITLE
Last version crashes when loaded in a Client UI

### ISSUE THREAD

**Issue by wise-coders** [googleapis/java-spanner-jdbc#729]
I try to use the latest JDBC driver with DbSchema.
This tool is loading the drivers dynamically, using java.net.URLClassLoader
When loading the latest single-driver-in-one-jar with dependencies, it gets the exception below. 
The driver version 2.3.2 works fine.
How can we avoid this?

![image](https://user-images.githubusercontent.com/60284259/152044037-1e72a571-5088-4fcf-9843-ce84428b76be.png)

**Comment by ansh0l** [comment]
@wise-coders: 

`I try to use the latest JDBC driver with DbSchema`: Can you confirm that you are using the JDBC version of github.com/googleapis/java-spanner-jdbc? The latest version we have is a [2.5.x] (https://github.com/googleapis/java-spanner-jdbc/blob/main/versions.txt).

**Comment by wise-coders** [comment]
I try to use version 2.5.9-SNAPSHOT-single-jar-with-dependencies, and it fails with 'Invalid signature file digest for Manifest main attributes'.
If I use 2.3.2 it works fine.

The fix would be a zip file with dependencies as separate jars.

**Comment by rajatbhatta** [comment]
@wise-coders: Thanks for bringing this to our notice. We are now advising customers to move away from fat jars(single jar with dependencies) as they lead to such unexpected errors. Having dependencies in separate jars is the way to go.
