### ISSUE TITLE
JDBC URL when project name contains minus characters

### ISSUE THREAD

**Issue by wise-coders** [googleapis/java-spanner-jdbc#730]
We have a case when the projectid contains minus characters. What should the URL look like? 
The driver version we use is 2.3.2.
Currently we use:
jdbc:cloudspanner:/projects/my-project/instances/my-instance/databases/my-db

**Comment by ansh0l** [comment]
@wise-coders : Please elaborate on what you mean by the `project name contains minus characters`. Are you talking of the `-` symbol, or is it some [Unicode confusable ](https://util.unicode.org/UnicodeJsps/confusables.jsp?a=test&r=None) character?

**Comment by ansh0l** [comment]
@wise-coders : Additionally, can you also confirm that you are using the JDBC version of github.com/googleapis/java-spanner-jdbc?

**Comment by rajatbhatta** [comment]
> But the version I tested is older, not the latest.

Can you tell us exactly which version you're using? And what is the error that you're facing when you use minus(-) character in the projectId directly in the connection URL?

**Comment by rajatbhatta** [comment]
@wise-coders: I was able to connect to Cloud Spanner with the v2.3.2.

Code snippet:

```
package com.google.cloud.spanner.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class MainClass {
  public static void main(String[] args) {
    String projectId = "my-test-project";
    String instanceId = "my-test-instance";
    String databaseId = "my-test-database";

    try (Connection connection =
        DriverManager.getConnection(
            String.format(
                "jdbc:cloudspanner:/projects/%s/instances/%s/databases/%s",
                projectId, instanceId, databaseId))) {
      try (Statement statement = connection.createStatement()) {
        try (ResultSet rs = statement.executeQuery("SELECT CURRENT_TIMESTAMP()")) {
          while (rs.next()) {
            System.out.printf(
                "Connected to Cloud Spanner at [%s]%n", rs.getTimestamp(1).toString());
          }
        }
      }
    } catch (SQLException e) {
      e.printStackTrace();
    }
  }
}
```
