### ISSUE TITLE
spanner-jdbc: JdbcTypeConverterTest failure

### ISSUE THREAD

**Issue by skuruppu** [googleapis/java-spanner-jdbc#85]
Tests in #73 fail as follows:
```
com.google.common.truth.ComparisonFailureWithFacts:
expected: 1969-12-31T22:59:59Z
but was : 1969-12-31T23:00:00Z
	at com.google.cloud.spanner.jdbc.JdbcTypeConverterTest.testToGoogleTimestamp(JdbcTypeConverterTest.java:608)
```

@olavloite if you could take a look that would be great.

**Comment by olavloite** [comment]
This is probably caused by https://www.github.com/googleapis/java-core/commit/1f8b6b4835aaa702ec94bbbde89ed90f519c935a (which is a good fix, BTW). I'll look into the test cases for the JDBC driver.
